export { default as side } from './side'
export { default as bottomBar } from './bottomBar'
export { default as topBar } from './topBar'
export { default as mainland } from './mainland'
// export { default as Sidebar } from './Sidebar/index.vue'
// export { default as TagsView } from './TagsView'
// export { default as AppMain } from './AppMain'
// export { default as Controlbtn } from './Controlbtn'
// export { default as TopBar } from './TopBar'
